steps:
  # 1단계 => docker-compose -f docker-compose.prod.yaml build
  - name: docker/compose:1.29.0
    args:
      - -f
      - docker-compose.prod.yaml
      - build

  # 2단계 => docker-compose -f docker-compose.prod.yaml push
  - name: docker/compose:1.29.0
    args:
      - -f
      - docker-compose.prod.yaml
      - push

  # 3딘계 => kubectl set image deployment/rungether-nestjs rungether-nestjs-sha256-1=asia.gcr.io/backend-371412/rungether-nestjs:0.3
  - name: gcr.io/cloud-builders/kubectl
    args:
      - set
      - image
      - deployment/rungether-nestjs
      - rungether-nestjs-sha256-1=asia.gcr.io/backend-371412/rungether-nestjs:0.5
    env:
      - CLOUDSDK_COMPUTE_ZONE=asia-northeast3
      - CLOUDSDK_CONTAINER_CLUSTER=autopilot-cluster-2
