version: '3.7'

services:
  backend:
    image: asia.gcr.io/backend-371412/rungether-nestjs:0.7
    platform: linux/x86_64
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - 3000:3000

